version: '3.6'

services:
  grav:
    image: grav-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/user/plugins/api
      - ./grav/accounts:/var/www/html/user/accounts
      - ./grav/pages:/var/www/html/user/pages
