siteadmin:
  readableName: Site Administrators
  description: 'The group of site administrators'
  icon: child
  access:
    api:
      users_read: true
      users_delete: true
      users_create: true
      users_edit: true
      plugins_read: true
      plugins_edit: true
      plugins_install: true
      plugins_uninstall: true
      configs_read: true
      configs_edit: true
    admin:
      login: true
    site:
      login: true
